export const ENDPOINTS = {
  AUTH: {
    LOGIN: "/api/auth/login",
    LOGOUT: "/api/auth/logout",
    ME: "/api/auth/me",
  },
  CLIENT_AUTH: {
    LOGIN: "/api/client-auth/login",
    LOGOUT: "/api/client-auth/logout",
    ME: "/api/client-auth/me",
  },
  PRICING_REQUESTS: {
    LIST: "/api/v1/pricing-requests",
    CREATE: "/api/v1/pricing-requests",
    DETAIL: (uid: string) => `/api/v1/pricing-requests/${uid}`,
    CANCEL: (uid: string) => `/api/v1/pricing-requests/${uid}/cancel`,
    MESSAGES: (uid: string) => `/api/v1/pricing-requests/${uid}/messages`,
    MESSAGES_STREAM: (uid: string) => `/api/v1/pricing-requests/${uid}/messages/stream`,
    ATTACHMENTS: (uid: string) => `/api/v1/pricing-requests/${uid}/attachments`,
    ATTACHMENT: (uid: string, attachmentUid: string) =>
      `/api/v1/pricing-requests/${uid}/attachments/${attachmentUid}`,
    SCOPE: (uid: string) => `/api/v1/pricing-requests/${uid}/scope`,
    CONFIRM_SCOPE: (uid: string) => `/api/v1/pricing-requests/${uid}/scope/confirm`,
    PHASES: (uid: string) => `/api/v1/pricing-requests/${uid}/scope/phases`,
    PHASE: (uid: string, phaseUid: string) =>
      `/api/v1/pricing-requests/${uid}/scope/phases/${phaseUid}`,
    TASKS: (uid: string, phaseUid: string) =>
      `/api/v1/pricing-requests/${uid}/scope/phases/${phaseUid}/tasks`,
    TASK: (uid: string, phaseUid: string, taskUid: string) =>
      `/api/v1/pricing-requests/${uid}/scope/phases/${phaseUid}/tasks/${taskUid}`,
    ASSUMPTIONS: (uid: string) => `/api/v1/pricing-requests/${uid}/scope/assumptions`,
    ASSUMPTION: (uid: string, assumptionUid: string) =>
      `/api/v1/pricing-requests/${uid}/scope/assumptions/${assumptionUid}`,
  },
  NEGOTIATIONS: {
    LIST: "/api/negotiations",
    SUBMIT: "/api/negotiations/submit",
  },
  CLIENTS: {
    LIST: "/api/clients",
    DETAIL: (id: string) => `/api/clients/${id}`,
  },
  USERS: {
    LIST: "/api/v1/users",
    CREATE: "/api/v1/users",
    DETAIL: (uid: string) => `/api/v1/users/${uid}`,
    DEACTIVATE: (uid: string) => `/api/v1/users/${uid}/deactivate`,
    ASSIGN_ROLE: (userUid: string, roleUid: string) => `/api/v1/users/${userUid}/roles/${roleUid}`,
    REMOVE_ROLE: (userUid: string, roleUid: string) => `/api/v1/users/${userUid}/roles/${roleUid}`,
  },
  ROLES: {
    LIST: "/api/v1/roles",
    CREATE: "/api/v1/roles",
    ASSIGN_PERMISSIONS: (roleUid: string) => `/api/v1/roles/${roleUid}/permissions`,
    PERMISSIONS: "/api/v1/permissions",
  },
  FIRM: {
    DETAILS: (uid: string) => `/v1/firms/${uid}`,
    UPDATE: (uid: string) => `/v1/firms/${uid}`,
    PRACTICE_AREAS: "/v1/practice-areas",
    PRACTICE_AREA_DEACTIVATE: (uid: string) => `/v1/practice-areas/${uid}/deactivate`,
    FEE_EARNER_LEVELS: "/v1/fee-earner-levels",
    RATE_CARDS: "/v1/rate-cards",
    RATE_CARD_ACTIVATE: (uid: string) => `/v1/rate-cards/${uid}/activate`,
    RATE_CARD_ENTRIES: (uid: string) => `/v1/rate-cards/${uid}/entries`,
    CLIENTS: "/api/v1/clients",
    CLIENT_DETAIL: (uid: string) => `/api/v1/clients/${uid}`,
    CLIENT_INVITE: (uid: string) => `/v1/clients/${uid}/portal-users`,
    GUARDRAILS: "/v1/firm/guardrails",
  },
  AUDIT_TRAIL: {
    BASE: "/v1/audit-trail",
    BY_UID: (uid: string) => `/v1/audit-trail/${uid}`,
  },
  DATA_ROOM: {
    SUMMARY: '/v1/data-room/summary',
    DATASETS: '/v1/data-room/datasets',
    DATASET_BY_UID: (uid: string) => `/v1/data-room/datasets/${uid}`,
    DATASET_DOCUMENTS: (uid: string) => `/v1/data-room/datasets/${uid}/documents`,
    DATASET_DOCUMENTS_BATCH: (uid: string) => `/v1/data-room/datasets/${uid}/documents/batch`,
    DOCUMENTS: '/v1/data-room/documents',
    DOCUMENT_BY_UID: (uid: string) => `/v1/data-room/documents/${uid}`,
    DOCUMENT_LOG: (uid: string) => `/v1/data-room/documents/${uid}/processing-logs`,
    DOCUMENT_RETRY: (uid: string) => `/v1/data-room/documents/${uid}/reprocess`,
    DOCUMENT_MAPPING: (uid: string) => `/v1/data-room/documents/${uid}/column-mapping`,
    RECORDS_PAST_MATTERS: '/v1/data-room/records/past-matters',
    RECORDS_TIME_ENTRIES: '/v1/data-room/records/time-entries',
    RECORDS_BILLING: '/v1/data-room/records/billing-history',
    RECORDS_RATE_HISTORY: '/v1/data-room/records/rate-card-history',
    RECORDS_BENCHMARKS: '/v1/data-room/records/market-benchmarks',
    MAPPING_TEMPLATES: '/v1/data-room/mapping-templates',
    MAPPING_TEMPLATE_DEFAULT: (uid: string) => `/v1/data-room/mapping-templates/${uid}/set-default`,
    FILE_STORAGE: '/v1/file-storage',
    FILE_STORAGE_BY_UID: (uid: string) => `/v1/file-storage/${uid}`,
    FILE_STORAGE_DOWNLOAD: (uid: string) => `/v1/file-storage/${uid}/download`,
  },
  AI_CONFIG: {
    PROVIDERS: '/api/v1/ai-config/providers',
    ACTIVE: '/api/v1/ai-config/providers/active',
    BY_UID: (uid: string) => `/api/v1/ai-config/providers/${uid}`,
    ACTIVATE: (uid: string) => `/api/v1/ai-config/providers/${uid}/activate`,
    TEST: (uid: string) => `/api/v1/ai-config/providers/${uid}/test`,
  },
} as const;

