export const PERMISSIONS = {
  REQUEST_READ: "REQUEST_READ",
  REQUEST_CREATE: "REQUEST_CREATE",
  REQUEST_WRITE: "REQUEST_WRITE",
  APPROVAL_READ: "APPROVAL_READ",
  APPROVAL_WRITE: "APPROVAL_WRITE",
  NEGOTIATION_READ: "NEGOTIATION_READ",
  NEGOTIATION_WRITE: "NEGOTIATION_WRITE",
  ANALYTICS_READ: "ANALYTICS_READ",
  KNOWLEDGE_READ: "KNOWLEDGE_READ",
  CLIENT_READ: "CLIENT_READ",
  AUDIT_READ: "AUDIT_READ",
  USER_READ: "USER_READ",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",
  ROLE_READ: "ROLE_READ",
  ROLE_CREATE: "ROLE_CREATE",
  ROLE_UPDATE: "ROLE_UPDATE",
  RATE_CARD_READ: "RATE_CARD_READ",
  PRACTICE_AREA_READ: "PRACTICE_AREA_READ",
  FIRM_READ: "FIRM_READ",
  DATA_ROOM_READ: "DATA_ROOM_READ",
  DATA_ROOM_MANAGE: "DATA_ROOM_MANAGE",
  AI_CONFIG_READ: "AI_CONFIG_READ",
  AI_CONFIG_MANAGE: "AI_CONFIG_MANAGE",
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export function hasPermission(userPermissions: string[], requiredPermission: string): boolean {
  return userPermissions.includes(requiredPermission);
}
