export const TOOL_LABELS: Record<string, string> = {
  get_current_scope: "Checking the current plan…",
  update_task: "Updating hours…",
  update_phase: "Updating a phase…",
  add_phase: "Adding a phase…",
  delete_phase: "Removing a phase…",
  add_task: "Adding a task…",
  delete_task: "Removing a task…",
  add_assumption: "Updating assumptions…",
  delete_assumption: "Updating assumptions…",
  generate_scope: "Drafting your engagement plan…",
  query_past_matters: "Reviewing comparable matters…",
  get_time_benchmarks: "Checking typical hours…",
  get_market_benchmarks: "Looking at market benchmarks…",
};

export const TOOL_SUCCESS_LABELS: Record<string, string> = {
  update_task: "Hours updated",
  update_phase: "Phase updated",
  add_phase: "Phase added",
  delete_phase: "Phase removed",
  add_task: "Task added",
  delete_task: "Task removed",
  add_assumption: "Assumption added",
  delete_assumption: "Assumption removed",
  generate_scope: "Plan drafted",
  query_past_matters: "Comparables ready",
  get_time_benchmarks: "Hour benchmarks ready",
  get_market_benchmarks: "Market context ready",
  get_current_scope: "Current plan loaded",
};
